name: location_example
description: Demonstrates how to use the location plugin.

dependencies:

  location: 2.3.5
  google_maps_flutter: ^0.5.4
  firebase_database: 3.0.7
  http: ^0.12.0+2
  json_serializable: ^3.2.3
  font_awesome_flutter: 8.5.0

  firebase_core: 0.4.0+8
  firebase_storage: 3.0.4
  image_cropper: 1.0.2
  image_picker: 0.6.0+17

  sensors: ^0.4.0+1
  speech_recognition: ^0.3.0+1
  url_launcher: ^5.1.4
  flutter_sms:
  countdown:
  flutter:
    sdk: flutter

  
   

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  assets:
    
    - assets/img/login_logo.png
    - assets/img/1.jpg
    - assets/img/2.jpg
    - assets/img/3.jpg
    - assets/img/4.jpg
    - assets/img/5.jpg
    - assets/img/6.jpg

  # To add assets to your application, add an assets section here, in
  # this "flutter" section, as in:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # To add assets from package dependencies, first ensure the asset
  # is in the lib/ directory of the dependency. Then,
  # refer to the asset with a path prefixed with
  # `packages/PACKAGE_NAME/`. Note: the `lib/` is implied, do not
  # include `lib/` in the asset path.
  #
  # Here is an example:
  #
  # assets:
  #  - packages/PACKAGE_NAME/path/to/asset

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
